<?php
/**
 * @file
 * Intergrate environment with test data.
 */


/**
 * Implements hook_default_search_api_server().
 */
function solr_server_default_search_api_server() {
  $items = array();
  $server = variable_get('solr_server_config', 'default');
  $config_path = drupal_get_path('module', 'solr_server') . "/servers/$server.conf";
  $config = file_get_contents($config_path);
  $items['solr'] = entity_import('search_api_server', '{
    "name" : "solr",
    "machine_name" : "solr",
    "description" : "solr search server",
    "class" : "search_api_solr_service",
    "options" : {'
    . $config .
    '},
    "enabled" : "1"
  }');
  return $items;
}
